### ISSUE TITLE
PaneSystem needs refactoring.

### ISSUE THREAD

**Issue by junsikshim** [junsikshim/react-pane-system#15]
After #10 being merged, `PaneSystem` has became too large in my opinion. `PaneSystem` and `InnerPaneSystem` are essentially the same, so we need to refactor them somehow.
Also, I'm trying to move all the splitters into a separate layer, so a wrapper is necessary.

For example,
```ts
<SomeContext>
  <PaneSystemContextRegistry>
    <InnerPaneSystem>
      ...
    </InnerPaneSystem>

    <SplitterLayer />
  </PaneSystemContextRegistry>
</SomeContext>
```

`SomeContext` may hold some values in which `InnerPaneSystem` and `SplitterLayer` both need.

@hchangjae Can you refactor this somehow?

**Comment by hchangjae** [comment]
The two codes are very similar, but there are some differences, making maintenance challenging.  
I'll take this.
